"use client";

import { useRef, useEffect, useState } from "react";
import { motion, useInView } from "framer-motion";

interface StatItem {
    value: number;
    suffix: string;
    label: string;
    description: string;
}

const stats: StatItem[] = [
    {
        value: 847,
        suffix: "K+",
        label: "Revenue Generated",
        description: "Total revenue generated by our users",
    },
    {
        value: 50,
        suffix: "K+",
        label: "Products Analyzed",
        description: "Products tracked and analyzed daily",
    },
    {
        value: 98,
        suffix: "%",
        label: "Accuracy Rate",
        description: "AI prediction accuracy",
    },
    {
        value: 12,
        suffix: "K+",
        label: "Active Users",
        description: "Dropshippers using Natade",
    },
];

function AnimatedNumber({ value, suffix }: { value: number; suffix: string }) {
    const [count, setCount] = useState(0);
    const ref = useRef<HTMLSpanElement>(null);
    const isInView = useInView(ref, { once: true });

    useEffect(() => {
        if (!isInView) return;

        let startTime: number;
        const duration = 2000;
        const startValue = 0;

        const animate = (currentTime: number) => {
            if (!startTime) startTime = currentTime;
            const progress = Math.min((currentTime - startTime) / duration, 1);
            const easeOutQuart = 1 - Math.pow(1 - progress, 4);
            const currentValue = Math.floor(startValue + (value - startValue) * easeOutQuart);
            setCount(currentValue);

            if (progress < 1) {
                requestAnimationFrame(animate);
            }
        };

        requestAnimationFrame(animate);
    }, [isInView, value]);

    return (
        <span ref={ref} className="tabular-nums">
            {count.toLocaleString()}
            {suffix}
        </span>
    );
}

export function Stats() {
    const containerRef = useRef<HTMLDivElement>(null);
    const isInView = useInView(containerRef, { once: true, margin: "-100px" });

    return (
        <section className="relative py-24 lg:py-32 overflow-hidden border-y border-white/5 bg-[#0A0A0B]">
            {/* Background */}
            <div className="absolute inset-0 bg-grid opacity-10" />
            <div className="absolute inset-0 bg-gradient-to-r from-[#0A0A0B] via-transparent to-[#0A0A0B]" />

            <div ref={containerRef} className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Section Header */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={isInView ? { opacity: 1, y: 0 } : {}}
                    transition={{ duration: 0.5 }}
                    className="text-center mb-16"
                >
                    <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-6 text-white tracking-tight">
                        Trusted by <span className="gradient-text">Thousands</span>
                    </h2>
                    <p className="text-lg text-zinc-400 max-w-xl mx-auto">
                        Join the growing community of successful dropshippers powered by Natade Intelligence.
                    </p>
                </motion.div>

                {/* Stats Grid */}
                <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 lg:gap-0 divide-y lg:divide-y-0 lg:divide-x divide-white/5 border border-white/5 rounded-3xl bg-white/[0.02]">
                    {stats.map((stat, index) => (
                        <motion.div
                            key={stat.label}
                            initial={{ opacity: 0, y: 20 }}
                            animate={isInView ? { opacity: 1, y: 0 } : {}}
                            transition={{ delay: 0.1 + index * 0.1, duration: 0.5 }}
                            className={`p-8 text-center ${index >= 2 ? 'pt-8' : ''}`} // Fix mobile padding
                        >
                            {/* Value */}
                            <div className="text-4xl sm:text-5xl lg:text-6xl font-bold gradient-text mb-4">
                                <AnimatedNumber value={stat.value} suffix={stat.suffix} />
                            </div>

                            {/* Label */}
                            <div className="font-semibold text-white mb-2">
                                {stat.label}
                            </div>

                            {/* Description */}
                            <div className="text-sm text-zinc-500">
                                {stat.description}
                            </div>
                        </motion.div>
                    ))}
                </div>

                {/* Logos Section - Infinite Marquee */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={isInView ? { opacity: 1, y: 0 } : {}}
                    transition={{ delay: 0.5 }}
                    className="mt-20 text-center"
                >
                    <p className="text-sm text-zinc-500 mb-8 uppercase tracking-widest font-medium">
                        Integrated with your favorite platforms
                    </p>

                    {/* Marquee Container */}
                    <div className="relative overflow-hidden">
                        {/* Fade edges */}
                        <div className="absolute left-0 top-0 bottom-0 w-20 bg-gradient-to-r from-[#0A0A0B] to-transparent z-10" />
                        <div className="absolute right-0 top-0 bottom-0 w-20 bg-gradient-to-l from-[#0A0A0B] to-transparent z-10" />

                        {/* Scrolling content */}
                        <div className="flex animate-marquee">
                            {/* First set */}
                            {["Shopify", "WooCommerce", "AliExpress", "Amazon", "eBay", "Etsy", "Lazada", "Tokopedia"].map(
                                (platform, index) => (
                                    <div
                                        key={`first-${platform}`}
                                        className="flex-shrink-0 mx-8 lg:mx-12"
                                    >
                                        <span className="font-semibold text-xl lg:text-2xl text-zinc-400 hover:text-white transition-colors duration-300 whitespace-nowrap">
                                            {platform}
                                        </span>
                                    </div>
                                )
                            )}
                            {/* Second set (duplicate for seamless loop) */}
                            {["Shopify", "WooCommerce", "AliExpress", "Amazon", "eBay", "Etsy", "Lazada", "Tokopedia"].map(
                                (platform, index) => (
                                    <div
                                        key={`second-${platform}`}
                                        className="flex-shrink-0 mx-8 lg:mx-12"
                                    >
                                        <span className="font-semibold text-xl lg:text-2xl text-zinc-400 hover:text-white transition-colors duration-300 whitespace-nowrap">
                                            {platform}
                                        </span>
                                    </div>
                                )
                            )}
                        </div>
                    </div>
                </motion.div>
            </div>

            {/* Marquee animation keyframes */}
            <style jsx>{`
                @keyframes marquee {
                    0% {
                        transform: translateX(0);
                    }
                    100% {
                        transform: translateX(-50%);
                    }
                }
                .animate-marquee {
                    animation: marquee 25s linear infinite;
                }
                .animate-marquee:hover {
                    animation-play-state: paused;
                }
            `}</style>
        </section>
    );
}

